services:
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data

  node:
    build:
      dockerfile: ./node-dockerfile-dev
    container_name: node-app
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./:/app
    # tty: true
volumes:
  postgres-data-dev:
